server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:tesdb;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  person:
    service:
      endpoint: http://localhost:8080/revenueNSW/persons/